Update GitHub Actions workflow for K2P build

diff --git a/.github/workflows/build_pure_K2P.yml b/.github/workflows/build_pure_K2P.yml
--- a/.github/workflows/build_pure_K2P.yml
+++ b/.github/workflows/build_pure_K2P.yml
@@ -1,104 +1,109 @@
-#修改TNAME: K2P 中的K2P为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
-name: Build-Pure-Padavan-K2P-5.0
+name: Build K2P
 
 on: 
   workflow_dispatch:
 
-
 jobs:
   build:
-    runs-on: ubuntu-24.04
-    if: github.event.repository.owner.id == github.event.sender.id
+    runs-on: ubuntu-22.04
 
     steps:
+    - name: Checkout
+      uses: actions/checkout@v4
+
+    - name: Set up Python 3.10
+      uses: actions/setup-python@v5
+      with:
+        python-version: '3.10'
+
     - name: Initialization environment
       env:
         DEBIAN_FRONTEND: noninteractive
       run: |
         sudo apt-get update
         sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
-        cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man \
-        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
+          cpio git gettext automake autopoint texinfo build-essential help2man \
+          pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
+
     - name: Clone source code
-      env:
-        KERNEL: 3.4
       run: |
-        git clone --depth=1 https://github.com/shallies/rt-n56u.git /opt/rt-n56u
-        cd /opt/rt-n56u/toolchain-mipsel
+        cd toolchain-mipsel
         sh dl_toolchain.sh
         mkdir -p /opt/images/
+
     - name: Build Firmware
       env:
-        TNAME: "K2P-5.0"
+        TNAME: "K2P-5.0 K2P"
       run: |
         cwd=`pwd`
         CONFIG_TOOLCHAIN_DIR=${cwd//\//\\\/}\\/toolchain-mipsel
-        cd /opt/rt-n56u/trunk
+        cd trunk
         sed -i "0,/FIRMWARE_BUILDS_REV.*$/s//FIRMWARE_BUILDS_REV=$(date +%Y%m%d)/" versions.inc
         for m in $TNAME;
         do
-        if [ ! -f configs/templates/$m.config ] ; then
-        echo "configs/templates/$m.config not found "
-        exit 1
-        fi
-        cp -f configs/templates/$m.config .config
-        #####################################################################################
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #删除配置项MENTOHUST
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config #删除配置项SOFTETHERVPN
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config #删除配置项SOFTETHERVPN
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config #删除配置项SOFTETHERVPN
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #删除配置项SCUTCLIENT
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #删除配置项SS plus+
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #删除配置项SS server
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项DNSFORWARDER
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #删除配置项adbyby plus+
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #删除配置项adbyby plus+
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #删除配置项adbyby plus+
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #删除配置项adbyby plus+
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #删除配置项阿里DDNS
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
-        ######################################################################
-        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
-        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> .config #SOFTETHERVPN
-        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> .config #SOFTETHERVPN
-        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> .config #SOFTETHERVPN
-        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
-        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config #SS plus+
-        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
-        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
-        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config #adbyby plus+
-        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config #内网穿透FRPC
-        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #内网穿透FRPS
-        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
-        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #阿里DDNS
-        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config #smartdns二进制文件
-        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #集成trojan执行文件，如果不集成，会从网上下载下来执行，不影响正常使用
-        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config #KP广告过滤
-        echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config #在线文件管理服务
-        echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #集成caddu执行文件，此文件有13M,请注意固件大小。如果不集成，会从网上下载下来执行，不影响正常使用
-        echo "CONFIG_FIRMWARE_INCLUDE_KUMASOCKS=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config #网易云解锁
-        echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #网易云解锁GO版本执行文件（4M多）注意固件超大小
-        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
-        if [ "$m" = "K2P-5.0" ] || [ "$m" = "DIR-878-5.0" ]; then
-        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #v2ray二进制文件
-        else
-        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #v2ray二进制文件
-        fi
-        ####################################################################################
-        sed -i "s/^CONFIG_TOOLCHAIN_DIR=.*$/CONFIG_TOOLCHAIN_DIR=${CONFIG_TOOLCHAIN_DIR}/g" .config
-        echo "Doing clear_tree_simple ..."
-        sudo ./clear_tree_simple
-        sudo ./build_firmware_modify_2 $m 0
-        sudo mv -f images/*.trx /opt/images/$m-3.4.3.9-099.trx
+          if [ ! -f configs/templates/$m.config ] ; then
+            echo "configs/templates/$m.config not found "
+            exit 1
+          fi
+          cp -f configs/templates/$m.config .config
+          #####################################################################################
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
+          ######################################################################
+          echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_KUMASOCKS=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config
+          if [ "$m" = "K2P-5.0" ] || [ "$m" = "DIR-878-5.0" ]; then
+            echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config
+          else
+            echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config
+          fi
+          ####################################################################################
+          sed -i "s/^CONFIG_TOOLCHAIN_DIR=.*$/CONFIG_TOOLCHAIN_DIR=${CONFIG_TOOLCHAIN_DIR}/g" .config
+          echo "Doing clear_tree_simple ..."
+          sudo ./clear_tree_simple
+          sudo ./build_firmware_modify $m 0
+          sudo mv -f images/*.trx /opt/images/$m-3.4.3.9-099.trx
         done
         echo "PackageName=Padavan-K2P-$(date +%Y%m%d)" >> $GITHUB_ENV
-    - name: 'Upload packages'
-      uses: actions/upload-artifact@master
+
+    - name: Upload packages
+      uses: actions/upload-artifact@v4
       with:
-       name: Padavan-packages
-       path: /opt/images
+        name: K2P
+        path: /opt/images/
